version: 2.8.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2022
configuration: Release
platform: Any CPU
init:
- ps: Install-Product node $env:nodejs_version
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  nodejs_version: 11
build_script:
- cmd: msbuild  -r -v:m  -t:rebuild -p:Configuration=Release IoTSharp.sln
artifacts:
- path: IoTSharp\bin\Release\*.nupkg
- path: IoTSharp.SDKs\IoTSharp.Sdk.MQTT\bin\Release\*.nupkg
- path: IoTSharp.SDKs\IoTSharp.Sdk.CSharp\bin\Release\*.nupkg
deploy: off